### ISSUE TITLE
style: where to put & when passing by address 

### ISSUE THREAD

**Issue by rileyjmurray** [BallisticLA/RandLAPACK#54]
In one of his reviews of PR #51, @PTNobel pointed out style inconsistency in our codebase.

If we pass a variable ``var`` of type ``T`` by address, we sometimes write ``T& var`` and sometimes write ``T &var``. This makes no difference from a correctness standpoint, but it does us no favors for readability. My preference is ``T &var, `` but I'm open to discussion on this.

In any case, we should have a dedicated PR for resolving this inconsistency. Maybe we can also adopt a C++ linter?

**Comment by TeachRaccooon** [comment]
I guess that this is a matter of difference in mine and yours styles of writing. 
I've always been using `T& var`, but it does not look like there is a set standard, and IBM page uses your style. 
I did not find the way they do it on the official C++ website, so my conclusion is "whatever y'all prefer."
