### ISSUE TITLE
RBKI termination criteria should use eps<T>, not eps<double>.

### ISSUE THREAD

**Issue by rileyjmurray** [BallisticLA/RandLAPACK#69]
This line https://github.com/BallisticLA/RandLAPACK/blob/f8e4226862405f6dd24fb1879da9a22d584ec38e/RandLAPACK/drivers/rl_rbki.hh#L379 gets machine epsilon for double-precision, even when ``T`` is something other than ``double``. It should be changed accordingly.

**Comment by TeachRaccooon** [comment]
fixed in https://github.com/BallisticLA/RandLAPACK/pull/92
