### ISSUE TITLE
Insane constructor for CQRRP_blocked

### ISSUE THREAD

**Issue by rileyjmurray** [BallisticLA/RandLAPACK#90]
https://github.com/BallisticLA/RandLAPACK/blob/9c0d8e317255d002277faba5f5aa9af409e5c5e2/RandLAPACK/drivers/rl_cqrrp.hh#L59-L71

everything is duplicated

**Comment by TeachRaccooon** [comment]
@rileyjmurray resolved in https://github.com/BallisticLA/RandLAPACK/pull/92
